# Generated by Django 2.2.4 on 2020-04-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='new_building',
        ),
        migrations.AddField(
            model_name='flat',
            name='Cтарое здание',
            field=models.NullBooleanField(primary_key=None, verbose_name='Новостройка'),
        ),
    ]
