# Generated by Django 2.2.4 on 2020-05-04 07:40

from django.db import migrations

def change_value(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year > 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200504_1115'),
    ]

    operations = [
        migrations.RunPython(change_value)
    ]
