# Generated by Django 2.2.4 on 2020-05-04 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_flat', to=settings.AUTH_USER_MODEL),
        ),
    ]
