# Generated by Django 2.2.4 on 2020-05-05 05:50

from django.db import migrations
import phonenumbers


def change_tel(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        tel = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(tel):
            flat.owner_phone_pure = phonenumbers.format_number(tel, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.save()

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20200504_1525'),
    ]

    operations = [
        migrations.RunPython(change_tel)
    ]
