# Generated by Django 2.2.4 on 2020-05-05 13:49

from django.db import migrations
from property.models import Flat, Owner


def add_flat_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owne in Owner.objects.all():
        flats = Flat.objects.filter(owner=owne.owner, owner_phone_pure=owne.owner_phone_pure)
        owne.flats.set(flats)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20200505_1237'),
    ]

    operations = [
        migrations.RunPython(add_flat_owner)
    ]
