# Generated by Django 2.2.4 on 2020-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20200511_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.NullBooleanField(choices=[(None, 'Неизвестно'), (False, 'Без балкона'), (True, 'С балконом')], verbose_name='Наличие балкона'),
        ),
    ]
