# Generated by Django 2.2.4 on 2020-05-11 10:50

from django.db import migrations

def change_none(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        if owner.owner == None:
            owner.owner = ''
            owner.save()
        if owner.owners_phonenumber == None:
            owner.owner = ''
            owner.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20200511_1431'),
    ]

    operations = [
        migrations.RunPython(change_none)
    ]
